// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usermgt/usermgt.proto

package usermgt_grpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	code "google.golang.org/genproto/googleapis/rpc/code"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NewUser struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewUser) Reset()         { *m = NewUser{} }
func (m *NewUser) String() string { return proto.CompactTextString(m) }
func (*NewUser) ProtoMessage()    {}
func (*NewUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_17e0a379904753f4, []int{0}
}

func (m *NewUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewUser.Unmarshal(m, b)
}
func (m *NewUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewUser.Marshal(b, m, deterministic)
}
func (m *NewUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewUser.Merge(m, src)
}
func (m *NewUser) XXX_Size() int {
	return xxx_messageInfo_NewUser.Size(m)
}
func (m *NewUser) XXX_DiscardUnknown() {
	xxx_messageInfo_NewUser.DiscardUnknown(m)
}

var xxx_messageInfo_NewUser proto.InternalMessageInfo

func (m *NewUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewUser) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

type User struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Id                   int32    `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	ErrorDetails         *Error   `protobuf:"bytes,4,opt,name=errorDetails,proto3" json:"errorDetails,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_17e0a379904753f4, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetErrorDetails() *Error {
	if m != nil {
		return m.ErrorDetails
	}
	return nil
}

type Error struct {
	Error                *Error_Status `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_17e0a379904753f4, []int{2}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetError() *Error_Status {
	if m != nil {
		return m.Error
	}
	return nil
}

type Error_Status struct {
	Code                 int32      `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Status               code.Code  `protobuf:"varint,4,opt,name=status,proto3,enum=google.rpc.Code" json:"status,omitempty"`
	Details              []*any.Any `protobuf:"bytes,5,rep,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Error_Status) Reset()         { *m = Error_Status{} }
func (m *Error_Status) String() string { return proto.CompactTextString(m) }
func (*Error_Status) ProtoMessage()    {}
func (*Error_Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_17e0a379904753f4, []int{2, 0}
}

func (m *Error_Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error_Status.Unmarshal(m, b)
}
func (m *Error_Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error_Status.Marshal(b, m, deterministic)
}
func (m *Error_Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error_Status.Merge(m, src)
}
func (m *Error_Status) XXX_Size() int {
	return xxx_messageInfo_Error_Status.Size(m)
}
func (m *Error_Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Error_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Error_Status proto.InternalMessageInfo

func (m *Error_Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error_Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error_Status) GetStatus() code.Code {
	if m != nil {
		return m.Status
	}
	return code.Code_OK
}

func (m *Error_Status) GetDetails() []*any.Any {
	if m != nil {
		return m.Details
	}
	return nil
}

func init() {
	proto.RegisterType((*NewUser)(nil), "usermgt.NewUser")
	proto.RegisterType((*User)(nil), "usermgt.User")
	proto.RegisterType((*Error)(nil), "usermgt.Error")
	proto.RegisterType((*Error_Status)(nil), "usermgt.Error.Status")
}

func init() { proto.RegisterFile("usermgt/usermgt.proto", fileDescriptor_17e0a379904753f4) }

var fileDescriptor_17e0a379904753f4 = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xcd, 0x4e, 0xab, 0x40,
	0x14, 0xbe, 0xb4, 0xa5, 0xa4, 0xa7, 0xb7, 0x4d, 0x33, 0xb9, 0x4d, 0xb8, 0xac, 0x08, 0x2b, 0x12,
	0xe3, 0xa0, 0xb8, 0x34, 0x2e, 0xb4, 0xba, 0xd4, 0xc5, 0x18, 0x37, 0x6e, 0xcc, 0x00, 0x23, 0xc5,
	0x14, 0x86, 0xcc, 0x0c, 0x35, 0x7d, 0x0b, 0xdf, 0xca, 0xd7, 0x32, 0x0c, 0x33, 0x4d, 0xba, 0x73,
	0x35, 0xe7, 0xfb, 0x39, 0xe1, 0x3b, 0x5f, 0x80, 0x75, 0x27, 0x99, 0xa8, 0x4b, 0x95, 0x98, 0x17,
	0xb7, 0x82, 0x2b, 0x8e, 0x3c, 0x03, 0x83, 0x75, 0xc9, 0x79, 0xb9, 0x63, 0x89, 0x68, 0xf3, 0x24,
	0xe7, 0x05, 0x1b, 0xf4, 0xe0, 0xbf, 0xa1, 0x35, 0xca, 0xba, 0xf7, 0x84, 0x36, 0x87, 0x41, 0x8a,
	0x12, 0xf0, 0x9e, 0xd8, 0xe7, 0x8b, 0x64, 0x02, 0x21, 0x98, 0x34, 0xb4, 0x66, 0xbe, 0x13, 0x3a,
	0xf1, 0x8c, 0xe8, 0x19, 0xad, 0x60, 0x4c, 0x4b, 0xe6, 0x8f, 0x42, 0x27, 0x76, 0x49, 0x3f, 0x46,
	0x2d, 0x4c, 0x7e, 0xef, 0x46, 0x4b, 0x18, 0x55, 0x85, 0x3f, 0xd6, 0xc4, 0xa8, 0x2a, 0x50, 0x0a,
	0x7f, 0x99, 0x10, 0x5c, 0xdc, 0x33, 0x45, 0xab, 0x9d, 0xf4, 0x27, 0xa1, 0x13, 0xcf, 0xd3, 0x25,
	0xb6, 0xf7, 0x3c, 0xf4, 0x22, 0x39, 0xf1, 0x44, 0xdf, 0x0e, 0xb8, 0x9a, 0x47, 0x67, 0xe0, 0x6a,
	0x45, 0x7f, 0x74, 0x9e, 0xae, 0x4f, 0xd7, 0xf0, 0xb3, 0xa2, 0xaa, 0x93, 0x64, 0xf0, 0x04, 0x5f,
	0x0e, 0x4c, 0x07, 0xa6, 0xcf, 0xda, 0xb7, 0xa1, 0xd7, 0x5c, 0xa2, 0x67, 0xe4, 0x83, 0x57, 0x33,
	0x29, 0x6d, 0xde, 0x19, 0xb1, 0x10, 0xc5, 0x30, 0x95, 0x7a, 0x4f, 0xa7, 0x5b, 0xa6, 0x2b, 0x3c,
	0xd4, 0x87, 0x45, 0x9b, 0xe3, 0x0d, 0x2f, 0x18, 0x31, 0x3a, 0xc2, 0xe0, 0x15, 0xe6, 0x10, 0x37,
	0x1c, 0xc7, 0xf3, 0xf4, 0x9f, 0xb5, 0xda, 0xa6, 0xf1, 0x6d, 0x73, 0x20, 0xd6, 0x94, 0xde, 0x80,
	0xd7, 0x77, 0xf7, 0x58, 0x2a, 0x94, 0xc2, 0x62, 0x23, 0x18, 0x55, 0xcc, 0xb6, 0xbf, 0x3a, 0x1e,
	0x63, 0x98, 0x60, 0x71, 0x64, 0x7a, 0x18, 0xfd, 0xb9, 0x4b, 0x5e, 0xcf, 0xcb, 0x4a, 0x6d, 0xbb,
	0x0c, 0xe7, 0xbc, 0x4e, 0xf6, 0xb4, 0xca, 0xb6, 0x74, 0xff, 0x41, 0xab, 0xe6, 0xe2, 0xd2, 0xfe,
	0x10, 0xd7, 0xe6, 0x7d, 0x2b, 0x45, 0x9b, 0x67, 0x53, 0x1d, 0xe3, 0xea, 0x27, 0x00, 0x00, 0xff,
	0xff, 0x69, 0x59, 0x94, 0xc1, 0x37, 0x02, 0x00, 0x00,
}
