// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package usermgt_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserMgtClient is the client API for UserMgt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserMgtClient interface {
	CreateNewUser(ctx context.Context, in *NewUser, opts ...grpc.CallOption) (*User, error)
}

type userMgtClient struct {
	cc grpc.ClientConnInterface
}

func NewUserMgtClient(cc grpc.ClientConnInterface) UserMgtClient {
	return &userMgtClient{cc}
}

func (c *userMgtClient) CreateNewUser(ctx context.Context, in *NewUser, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/usermgt.UserMgt/CreateNewUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserMgtServer is the server API for UserMgt service.
// All implementations must embed UnimplementedUserMgtServer
// for forward compatibility
type UserMgtServer interface {
	CreateNewUser(context.Context, *NewUser) (*User, error)
	mustEmbedUnimplementedUserMgtServer()
}

// UnimplementedUserMgtServer must be embedded to have forward compatible implementations.
type UnimplementedUserMgtServer struct {
}

func (UnimplementedUserMgtServer) CreateNewUser(context.Context, *NewUser) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNewUser not implemented")
}
func (UnimplementedUserMgtServer) mustEmbedUnimplementedUserMgtServer() {}

// UnsafeUserMgtServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserMgtServer will
// result in compilation errors.
type UnsafeUserMgtServer interface {
	mustEmbedUnimplementedUserMgtServer()
}

func RegisterUserMgtServer(s grpc.ServiceRegistrar, srv UserMgtServer) {
	s.RegisterService(&UserMgt_ServiceDesc, srv)
}

func _UserMgt_CreateNewUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserMgtServer).CreateNewUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usermgt.UserMgt/CreateNewUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserMgtServer).CreateNewUser(ctx, req.(*NewUser))
	}
	return interceptor(ctx, in, info, handler)
}

// UserMgt_ServiceDesc is the grpc.ServiceDesc for UserMgt service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserMgt_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "usermgt.UserMgt",
	HandlerType: (*UserMgtServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNewUser",
			Handler:    _UserMgt_CreateNewUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "usermgt/usermgt.proto",
}
